### PR TITLE
This cryopod rework turned into a stasis refactor

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

Removes stasis beds from being readily accessible, and makes cryopods apply stasis to their occupants.

## Why It's Good For The Game

Stasis beds bad

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.
## Changelog

:cl:
balance: stasis beds have been decommissioned from public use
balance: cryo cells now apply stasis to it's occupants
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
i have no idea how to convert this to a draft, either way not ready to merge yet

**Comment by NullDagaf** [comment]
need to fix cells not removing stasis on turning off, as well as general testing

**Comment by ChungusGamer666** [comment]
Massive medical balance implications and mapping issues. Cannot be merged unless thoroughly testmerge.

**Comment by ChungusGamer666** [comment]
its so over

**Pull request closed without merging**
